/* Server Version: WI-V6.3.1.4481 Firebird 1.5.  ODS Version: 10.1. */

SET NAMES NONE;

SET SQL DIALECT 3;

DROP TABLE IC_MAT_STK_RESEVED;
COMMIT WORK;

/* Create Table... */
CREATE TABLE IC_STOCK_RESERVED(DOC_NO VARCHAR(15) CHARACTER SET NONE NOT NULL,
DOC_DATE TIMESTAMP NOT NULL,
LOT_CD VARCHAR(15) CHARACTER SET NONE NOT NULL,
PURCHASE_DATE TIMESTAMP NOT NULL,
REF_NO VARCHAR(15) CHARACTER SET NONE NOT NULL,
REF_DATE TIMESTAMP NOT NULL,
STOCK_CD VARCHAR15 NOT NULL,
GROUP_ID VARCHAR(10) CHARACTER SET NONE NOT NULL,
UOM_CD VARCHAR4 NOT NULL,
QTY FLOAT NOT NULL,
UPDATE_USER VARCHAR(10) CHARACTER SET NONE,
UPDATE_DATE TIMESTAMP);
COMMIT WORK;

/* Create Views... */

/* Create Primary Key... */
ALTER TABLE IC_STOCK_RESERVED ADD CONSTRAINT PK_IC_STOCK_RESERVED PRIMARY KEY (DOC_NO,DOC_DATE,LOT_CD,PURCHASE_DATE,REF_NO,REF_DATE,GROUP_ID,UOM_CD,STOCK_CD);
COMMIT WORK;
/* Create Trigger... */
SET TERM ^ ;
CREATE TRIGGER TD_PL_REQ_DT_AD0 FOR PL_REQ_DT
INACTIVE AFTER DELETE POSITION 0 
AS
begin
  DELETE FROM IC_STOCK_RESERVED
  WHERE DOC_NO = old.DOC_NO
  AND DOC_DATE = old.DOC_DATE
  AND LOT_CD = old.lot_no
  AND PURCHASE_DATE = old.purchase_date
  AND REF_NO = old.REF_NO
  AND REF_DATE = old.REF_DATE
  AND STOCK_CD = old.item_code
  AND GROUP_ID = old.group_id
  AND UOM_CD = old.uom ;
end
^

SET TERM ; ^
COMMIT WORK;
SET TERM ^ ;
CREATE TRIGGER TI_PL_REQ_DT_AI0 FOR PL_REQ_DT
INACTIVE AFTER INSERT POSITION 0 
AS
begin
    INSERT into IC_STOCK_RESERVED  VALUES(NEW.doc_no,NEW.DOC_DATE,NEW.lot_no,NEW.purchase_date,
    NEW.ref_no,NEW.ref_date,NEW.item_code,NEW.group_id,NEW.uom,NEW.qty,'jrx',current_timestamp);
end
^

SET TERM ; ^
COMMIT WORK;
SET TERM ^ ;
CREATE TRIGGER TU_PL_REQ_DT_AU0 FOR PL_REQ_DT
INACTIVE AFTER UPDATE POSITION 0 
AS
begin
  UPDATE IC_STOCK_RESERVED
  SET QTY = NEW.qty
  WHERE DOC_NO = NEW.DOC_NO
  AND DOC_DATE = NEW.DOC_DATE
  AND LOT_CD = NEW.lot_no
  AND PURCHASE_DATE = NEW.purchase_date
  AND REF_NO = NEW.REF_NO
  AND REF_DATE = NEW.REF_DATE
  AND STOCK_CD = NEW.item_code
  AND GROUP_ID = NEW.group_id
  AND UOM_CD = NEW.uom ;
end
^

SET TERM ; ^
COMMIT WORK;

/* DROP: -- GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON IC_MAT_STK_RESEVED TO REPL WITH GRANT OPTION; */
REVOKE GRANT OPTION FOR DELETE, INSERT, SELECT, UPDATE, REFERENCES ON IC_MAT_STK_RESEVED FROM REPL;
COMMIT WORK;
/* DROP: -- GRANT SELECT ON IC_MAT_STK_RESEVED TO TRIGGER IC_MAT_STK_DT_LINK_AD0; */
REVOKE SELECT ON IC_MAT_STK_RESEVED FROM TRIGGER IC_MAT_STK_DT_LINK_AD0;
COMMIT WORK;
/* Create(Add) Crant */
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON IC_STOCK_RESERVED TO REPL WITH GRANT OPTION;
COMMIT WORK;


