CREATE table IC_DEFINEDGROUP(
  DEF_CODE VARCHAR(10)/**/ NOT NULL primary KEY,
  USER_ID VARCHAR(10) NOT NULL,
  STOCK_GROUP VARCHAR(4) NOT NULL,
  DEF_DESCS VARCHAR(100) ,
  UPDATE_DATE TIMESTAMP
)




